apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount.variables.replicaCount.value }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.variables.image.value }}"
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-c"]
        args: ["/root/openface/demos/web/start-servers.sh"]
        env:
        - name: WEBSOCKET_NODE_PORT
          value: "{{ .Values.service.variables.websocketNodePort.value }}"
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9000
          name: websocket
        resources:
          requests:
            cpu: {{ .Values.resources.variables.cpuRequest.value }}m
            memory: {{ .Values.resources.variables.memoryRequest.value }}Mi
