apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.httpPort }}
    name: http
    targetPort: {{ .Values.service.httpPort }}
    nodePort: {{.Values.service.httpNodePort}}
  - port: {{ .Values.service.websocketPort }}
    name: websocket
    targetPort: {{ .Values.service.websocketPort }}
    nodePort: {{.Values.service.websocketNodePort}}
  selector:
    app: {{ template "fullname" . }}
