apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.config.variables.replicaCount.value }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.config.variables.image.value }}"
        imagePullPolicy: {{ .Values.config.variables.imagepullpolicy.value }}
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: {{ .Values.config.variables.cpuRequest.value }}m
            memory: {{ .Values.config.variables.memoryRequest.value }}Mi
        
