isNewTemplate: true

image:
   name: "image"
   description: "Image Info"
   type: "string"
   required: true
   variables:
     image:
       name: "image"
       label: "image"
       description: "The image of app"
       required: true
       value: "registry.harbor:5000/sky-firmament/tomcat:8.5.31"
       type: "string"    
     policyType:
       name: "policyType"
       label: "policy type"
       description: "The type of image pull policy"
       required: true
       value: "IfNotPresent"
       type: "string"

resources:
   name: "reosurce info"
   description: "Reosurce Info"
   type: "string"
   required: true
   variables:
     cpuRequest:
       name: "cpuRequest"
       label: "cpu(m)"
       description: "CPU, in cores. (500m = 0.5 cores)"
       required: true
       value: 100
       type: "int"
     memoryRequest:
       name: "memoryRequest"
       label: "memory(MB)"
       description: "Memory, in MB. (1GB = 1024 MB)"
       required: true
       value: 256
       type: "int"

persistence:
   name: "storage"
   description: "Persistent Storage"
   type: "checkbox"
   required: true
   enabled: false
   variables:
     mountPath:
       name: "mountPath"
       label: "Mount Path"
       description: "The path within the container at which the volume should be mounted"
       required: true
       value: "/usr/local/tomcat/webapps"
       type: "string"
     size:
       name: "sizeRequest"
       label: "storage(GB)"
       description: "Storage, in GB. (1GB = 1024 MB)"
       required: true
       value: 1
       type: "int"
     storagePool:
       name: "storagePool"
       label: "storagePool"
       description: "storage pool for volume, use default pool if value is null"
       required: false
       value: ""
       type: "string"

service:
   name: "service"
   description: "Service Info"
   type: "string"
   required: true
   variables:
     type:
       name: "serviceType"
       label: "service type"
       description: "The type of service"
       required: true
       value: "LoadBalancer"
       type: "string"
     port:
       name: "servicePort"
       label: "service port"
       description: "The port of service"
       required: true
       value: "8080"
       type: "string"
config:
  name: "config"
  description: "custom config"
  type: "text"
  required: true
  variables:
    path:
      name: "path"
      label: "file path"
      description: "The path of config file"
      required: true
      value: "/usr/local/tomcat/conf/server.xml"
      type: "string"
    content: 
      name: "content"
      label: "content"
      description: "The content of config file"
      required: true
      type: "text"
      value: |-
        <?xml version="1.0" encoding="UTF-8"?>
        <!--  zw-test --> 
        <Server port="8005" shutdown="SHUTDOWN">
          <Listener className="org.apache.catalina.startup.VersionLoggerListener" />
          <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
          <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
          <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
          <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener" />
          <GlobalNamingResources>
            <Resource name="UserDatabase" auth="Container"
                      type="org.apache.catalina.UserDatabase"
                      description="User database that can be updated and saved"
                      factory="org.apache.catalina.users.MemoryUserDatabaseFactory"
                      pathname="conf/tomcat-users.xml" />
          </GlobalNamingResources>
          <Service name="Catalina">
            <Connector port="8080" protocol="HTTP/1.1"
                       connectionTimeout="20000"
                       redirectPort="8443" />
            <Connector port="8009" protocol="AJP/1.3" redirectPort="8443" />
            <Engine name="Catalina" defaultHost="localhost">
              <Realm className="org.apache.catalina.realm.LockOutRealm">
                <Realm className="org.apache.catalina.realm.UserDatabaseRealm"
                       resourceName="UserDatabase"/>
              </Realm>
              <Host name="localhost"  appBase="webapps"
                    unpackWARs="true" autoDeploy="true">
                <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
                       prefix="localhost_access_log" suffix=".txt"
                       pattern="%h %l %u %t &quot;%r&quot; %s %b" />
              </Host>
            </Engine>
          </Service>
        </Server>
