description: MySQL is a fast, reliable, scalable, and easy to use open-source relational
  database system. MySQL Server is intended for mission-critical, heavy-load production
  systems as well as for embedding into mass-deployed software.
engine: gotpl
home: https://mysql.com
icon: https://bitnami.com/assets/stacks/mysql/img/mysql-stack-220x234.png
keywords:
- mysql
- database
- sql
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: mysql
sources:
- https://github.com/bitnami/bitnami-docker-mysql
version: 5.7.20
