{{- if .Values.hpa.enabled }}
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2alpha1
metadata:
  name: {{ .Release.Name }}-redis-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ .Release.Name }}-redis
  minReplicas: {{ .Values.hpa.variables.minReplicas.value }}
  maxReplicas: {{ .Values.hpa.variables.maxReplicas.value }}
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: {{ .Release.Name }}-redis
      metricName: {{ .Values.hpa.variables.metricName.value }}
      targetValue: {{ .Values.hpa.variables.targetValue.value }}
{{- end -}}