apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-exporter
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: exporter
    port: 9104
    targetPort: exporter
  selector:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name }}
