apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    available_panels: >
      {"Commands":"5","服务IO":"4","并发连接数":"3","服务启动时间":"1"}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.variables.type.value }}
  ports:
  - port: {{ .Values.service.variables.externalPort.value }}
    targetPort: {{ .Values.service.variables.internalPort.value }}
  {{- if ( and (eq .Values.service.variables.type.value "NodePort") (.Values.service.variables.nodePort.value) ) }}
    nodePort: {{ .Values.service.variables.nodePort.value }}
  {{- end }}
    protocol: TCP
    name: mysql
  selector:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name }}
