apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  - name: exporter
    port: 9104
    targetPort: exporter
  selector:
    app: {{ template "fullname" . }}
