# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Master:
  Name: jenkins-master
  Image: "registry.harbor:5000/skyform-ecp/jenkins-master-k8s"
  ImageTag: "v0.6.0"
  ImagePullPolicy: "IfNotPresent"
  Component: "jenkins-master"
  AdminUser: admin
  AdminPassword: admin
  Cpu: "200m"
  Memory: "256Mi"
# Set min/max heap here if needed with:
# JavaOpts: "-Xms512m -Xmx512m"
  ServicePort: 8080
# For minikube, set this to NodePort, elsewhere use LoadBalancer
  ServiceType: NodePort
  NodePort: 31091
  ContainerPort: 8080
  SlaveListenerPort: 50000
  LoadBalancerSourceRanges:
  - 0.0.0.0/0

Agent:
  Image: registry.harbor:5000/skyform-ecp/jnlp-slave
  ImageTag: 2.52
  Cpu: "200m"
  Memory: "256Mi"

Persistence:
  Enabled: false
  StorageClass: generic
  AccessMode: ReadWriteOnce
  Size: 8Gi
