apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.variables.type.value }}
  ports:
    - port: {{ .Values.service.variables.port.value }}
      targetPort: {{ .Values.service.variables.port.value }}
      {{- if ( and (eq .Values.service.variables.type.value "NodePort") (.Values.service.variables.nodePort.value) ) }}
      nodePort: {{ .Values.service.variables.nodePort.value }}
      {{- end }}
      protocol: TCP
      name: "api"
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
