isNewTemplate: true

image:
   name: "image"
   description: "Image Info"
   type: "string"
   required: true
   variables:
     image:
       name: "image"
       label: "image"
       description: "The image of app"
       required: true
       value: "registry.harbor:5000/smile/redis:4.0.8r0"
       type: "string"    
     policyType:
       name: "policyType"
       label: "policy type"
       description: "The type of image pull policy"
       required: true
       value: "Always"
       type: "string"

resources:
   name: "reosurce info"
   description: "Reosurce Info"
   type: "string"
   required: true
   variables:
     cpuRequest:
       name: "cpuRequest"
       label: "cpu(m)"
       description: "CPU, in cores. (500m = 0.5 cores)"
       required: true
       value: 100
       type: "int"
     memoryRequest:
       name: "memoryRequest"
       label: "memory(MB)"
       description: "Memory, in MB. (1GB = 1024 MB)"
       required: true
       value: 256
       type: "int"
     replicas:
       name: "replicas"
       label: "replicas"
       description: "the number of redis server replicas"
       required: true
       value: 3
       type: "int"
sentinelResources:
   name: "sentinel reosurce info"
   description: "sentinel Reosurce Info"
   type: "string"
   required: true
   variables:
     cpuRequest:
       name: "cpuRequest"
       label: "cpu(m)"
       description: "CPU, in cores. (500m = 0.5 cores)"
       required: true
       value: 100
       type: "int"
     memoryRequest:
       name: "memoryRequest"
       label: "memory(MB)"
       description: "Memory, in MB. (1GB = 1024 MB)"
       required: true
       value: 256
       type: "int"
     replicas:
       name: "replicas"
       label: "replicas"
       description: "the number of redis sentinel replicas"
       required: true
       value: 3
       type: "int"
service:
   name: "service"
   description: "Service Info"
   type: "string"
   required: true
   variables:
     type:
       name: "serviceType"
       label: "service type"
       description: "The type of service"
       required: true
       value: "LoadBalancer"
       type: "selectbox"
       selectValue: ["ClusterIP", "LoadBalancer", "NodePort"]
     port:
       name: "servicePort"
       label: "service port"
       description: "The port of service"
       required: true
       value: "6379"
       type: "string"
     nodePort:
       name: "nodePort"
       label: "nodePort"
       description: "The nodePort of service,range 30000-32767,only available when serviceType is NodePort"
       required: false
       value: ""
       type: "string"
config:
  name: "config"
  description: "custom config"
  type: "string"
  required: true
  variables:
    password: 
      name: "password"
      label: "redis password"
      description: "The password of redis"
      required: true
      type: "string"
      value: "password"