{{- if .Values.cluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-discovery
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: {{ .Values.service.variables.externalPort.value }}
    targetPort: 8983
    protocol: TCP
    name: api
  selector:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name }}
{{- end }}
