apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-worker
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  completions: {{ .Values.worker.variables.replicaCount.value }}
  parallelism: {{ .Values.worker.variables.replicaCount.value }}
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}
        role: worker
        release: {{ .Release.Name }}
        job: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{  template "fullname" . }}
      containers:
        - name: worker
          image: "{{ .Values.worker.variables.image.value }}"
          command: ["bootstrap"]
          args:
          - --ps_num={{ .Values.ps.variables.replicaCount.value }}
          - --worker_num={{ .Values.worker.variables.replicaCount.value }}
          - --job_name={{ .Release.Name }}
          - --role=worker
          - --cmd={{ .Values.cmd.variables.cmd.value }} --data_dir={{ .Values.persistence.variables.dataDir.value }} --model_dir={{ .Values.persistence.variables.modelDir.value }} --log_dir={{ .Values.persistence.variables.logDir.value }}
          env:
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_DIR
              value: {{ .Values.persistence.variables.logDir.value }}
          ports:
          - containerPort: 2222
          resources:
            limits:
              cpu: {{ .Values.worker.variables.cpuRequest.value }}m
              memory: {{ .Values.worker.variables.cpuRequest.value }}Mi
            requests:
              cpu: {{ .Values.worker.variables.cpuRequest.value }}m
              memory: {{ .Values.worker.variables.cpuRequest.value }}Mi
          volumeMounts:
          - name: data
            mountPath: {{ .Values.persistence.variables.mountPath.value }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.variables.pvc.value }}
