{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "rabbitmq.fullname" . }}
spec:
  accessModes:
    - {{ .Values.persistence.variables.accessMode.type | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.variables.size.value | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
