{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.variables.storagePool.value }}
  storageClassName: {{ .Values.persistence.variables.storagePool.value | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.variables.size.value | quote }}
{{- end }}
