apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-management
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.managementService.variables.type.value }}
  ports:
  - name: api
    port: {{ .Values.managementService.variables.port.value }}
    targetPort: {{ .Values.managementService.variables.port.value }}
    {{- if eq .Values.managementService.variables.type.value  "NodePort" }}
    nodePort: {{ .Values.managementService.variables.nodePort.value }}
    {{- end }}
  selector:
    app: {{ template "fullname" . }}
