isNewTemplate: true

config:
  name: "config"
  description: "base config"
  type: "string"
  required: true
  variables:
    replicaCount:
      name: "replicaCount"
      label: "replicaCount"
      description: "replica count"
      required: true
      value: 1
      type: "int"
    image:
      name: "image"
      label: "Image"
      description: "The image of mnist demo."
      required: true
      value: "docker.io/rivernet/mnist-demo:4.1"
      type: "string"
    imagepullpolicy:
      name: "imagepullpolicy"
      label: "Image Pull Policy"
      description: "Supported values: IfNotPresent, Always. Case sensitive."
      value: "IfNotPresent"
      type: "string"
    serviceType:
      name: "servicetype"
      label: "Service Type"
      description: "Supported values: LoadBalancer, NodePort, ClusterIP, ExternalName. Case sensitive."
      value: "NodePort"
      type: "string"
    cpuRequest:
      name: "cpuRequest"
      label: "CPU (m)"
      description: "CPU, in cores. (500m = 0.5 cores)"
      required: true
      value: 300
      type: "int"
    memoryRequest:
      name: "memoryRequest"
      label: "Memory (MB)"
      description: "Memory, in MB. (1GB = 1024 MB)"
      required: true
      value: 512
      type: "int"

