name: jupyter
version: 1.0.0
appVersion: 4.1
description: Chart for Jupyter Notebook with Tensorflow support.
keywords:
- jupyter
- notebook
- ipython
- python
home: http://jupyter.org/
maintainers:
- name: Meng Ding
  email: dingmeng@gmail.com
engine: gotpl
