isNewTemplate: true

persistence:
  name: "storage"
  description: "Persistent Storage"
  type: "string"
  required: true  
  variables:
    pvc:
      name: "pvc"
      label: "PVC Name"
      description: "The name of the persistent volume claim"
      required: true
      value: ""
      type: "string"
    mountPath:
      name: "mountPath"
      label: "Mount Path"
      description: "The path within the container at which the volume should be mounted"
      required: true
      value: "/notebooks"
      type: "string"

jupyter:
  name: "jupyter"
  description: "Jupyter Notebook"
  type: "string"
  required: true
  variables:
    image:
      name: "image"
      label: "Image"
      description: "The image of Jupyter Notebook."
      required: true
      value: "docker.io/rivernet/jupyter:4.2"
      type: "string"
    imagepullpolicy:
      name: "imagepullpolicy"
      label: "Image Pull Policy"
      description: "Supported values: IfNotPresent, Always. Case sensitive."
      value: "IfNotPresent"
      type: "string"
    serviceType:
      name: "servicetype"
      label: "Service Type"
      description: "Supported values: LoadBalancer, NodePort, ClusterIP, ExternalName. Case sensitive."
      value: "NodePort"
      type: "string"
    cpuRequest:
      name: "cpuRequest"
      label: "CPU (m)"
      description: "CPU, in cores. (500m = 0.5 cores)"
      required: true
      value: 300
      type: "int"
    memoryRequest:
      name: "memoryRequest"
      label: "Memory (MB)"
      description: "Memory, in MB. (1GB = 1024 MB)"
      required: true
      value: 512
      type: "int"  
