apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  completions: {{ .Values.mxnet.variables.replicaCount.value }}
  parallelism: {{ .Values.mxnet.variables.replicaCount.value }}
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}
        release: {{ .Release.Name }}
        job: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: worker
          image: "{{ .Values.mxnet.variables.image.value }}"
          command: ["bootstrap"]
          args:
          - --worker_num={{ .Values.mxnet.variables.replicaCount.value }}
          - --job_name={{ .Release.Name }}
          - --cmd={{ .Values.cmd.variables.cmd.value }}
          env:
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: KUBERNETES_URL
              value: 192.168.254.42:8080
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
          - containerPort: 22
          resources:
            limits:
              cpu: {{ .Values.mxnet.variables.cpuRequest.value }}m
              memory: {{ .Values.mxnet.variables.cpuRequest.value }}Mi
            requests:
              cpu: {{ .Values.mxnet.variables.cpuRequest.value }}m
              memory: {{ .Values.mxnet.variables.cpuRequest.value }}Mi
          volumeMounts:
          - name: data
            mountPath: {{ .Values.persistence.variables.mountPath.value }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.variables.pvc.value }}
