apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "redis-ha.fullname" . }}-sentinel
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.sentinelResources.variables.replicas.value }}
  template:
    metadata:
      labels:
        app: {{ template "redis-ha.name" . }}
        release: {{ .Release.Name }}
        component: sentinel
        name: {{ template "redis-ha.fullname" . }}-sentinel
    spec:
      serviceAccountName: {{ template "redis-ha.fullname" . }}
      containers:
      - name: sentinel
        image: {{ .Values.image.variables.image.value }}
        imagePullPolicy: {{ default "" .Values.image.variables.policyType.value | quote }}
        resources:
          requests:
             cpu: {{ .Values.sentinelResources.variables.cpuRequest.value }}m
             memory: {{ .Values.sentinelResources.variables.memoryRequest.value }}Mi
        env:
          - name: SENTINEL
            value: "true"
          - name: REDIS_CHART_PREFIX
            value: {{ template "redis-ha.fullname" . }}-
{{- if .Values.config.variables.password.value }}
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: {{ template "redis-ha.fullname" . }}
                key: auth
{{- end }}
        ports:
          - containerPort: 26379
