apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis-ha.fullname" . }}-master-svc
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.variables.type.value }}
  ports:
  - name: api
    port: {{ .Values.service.variables.port.value }}
    targetPort: {{ .Values.service.variables.port.value }}
    {{- if eq .Values.service.variables.type.value  "NodePort" }}
    nodePort: {{ .Values.service.variables.nodePort.value }}
    {{- end }}
  selector:
    app: {{ template "redis-ha.name" . }}
    release: "{{ .Release.Name }}"
    redis-node: "true"
    redis-role: "master"
