{{- if .Values.config.variables.password.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redis-ha.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  auth: {{ .Values.config.variables.password.value | b64enc | quote }}
{{- end -}}
