isNewTemplate: true

image:
   name: "image"
   description: "Image Info"
   type: "string"
   required: true
   variables:
     image:
       name: "image"
       label: "image"
       description: "The image of app"
       required: true
       value: "registry.harbor:5000/sky-firmament/rabbitmq:3.7.5-management"
       type: "string"    
     policyType:
       name: "policyType"
       label: "policy type"
       description: "The type of image pull policy"
       required: true
       value: "Always"
       type: "string"

resources:
   name: "reosurce info"
   description: "Reosurce Info"
   type: "string"
   required: true
   variables:
     cpuRequest:
       name: "cpuRequest"
       label: "cpu(m)"
       description: "CPU, in cores. (500m = 0.5 cores)"
       required: true
       value: 100
       type: "int"
     memoryRequest:
       name: "memoryRequest"
       label: "memory(MB)"
       description: "Memory, in MB. (1GB = 1024 MB)"
       required: true
       value: 256
       type: "int"

persistence:
   name: "storage"
   description: "Persistent Storage"
   type: "checkbox"
   required: true
   enabled: true
   variables:
     mountPath:
       name: "mountPath"
       label: "Mount Path"
       description: "The path within the container at which the volume should be mounted"
       required: true
       value: "/var/lib/rabbitmq"
       type: "string"
     size:
       name: "sizeRequest"
       label: "storage(GB)"
       description: "Storage, in GB. (1GB = 1024 MB)"
       required: true
       value: 1
       type: "int"
     storagePool:
       name: "storagePool"
       label: "storagePool"
       description: "storage pool for volume, use default pool if value is null"
       required: false
       value: ""
       type: "string"
     type:
       name: "volumeType"
       label: "volume type"
       description: "The type of volume"
       required: true
       value: "Normal"
       selectValue: ["Normal", "Fast"]
       type: "selectbox"

service:
   name: "service"
   description: "Service Info"
   type: "string"
   required: true
   variables:
     type:
       name: "serviceType"
       label: "service type"
       description: "The type of service"
       required: true
       value: "LoadBalancer"
       type: "selectbox"
       selectValue: ["ClusterIP", "LoadBalancer", "NodePort"]
     port:
       name: "servicePort"
       label: "service port"
       description: "The port of service"
       required: true
       value: "5672"
       type: "string"
     nodePort:
       name: "nodePort"
       label: "nodePort"
       description: "The nodePort of service,range 30000-32767,only available when serviceType is NodePort"
       required: false
       value: ""
       type: "string"
managementService:
   name: "managementService"
   description: "management Service Info"
   type: "string"
   required: true
   variables:
     type:
       name: "serviceType"
       label: "service type"
       description: "The type of service"
       required: true
       value: "LoadBalancer"
       type: "selectbox"
       selectValue: ["ClusterIP", "LoadBalancer", "NodePort"]
     port:
       name: "servicePort"
       label: "service port"
       description: "The port of service"
       required: true
       value: "15672"
       type: "string" 
     nodePort:
       name: "nodePort"
       label: "nodePort"
       description: "The nodePort of service,range 30000-32767,only available when serviceType is NodePort"
       required: false
       value: ""
       type: "string"
config:
  name: "config"
  description: "custom config"
  type: "text"
  required: true
  variables:
    config: 
      name: "config"
      label: "rabbitmq.conf"
      path: "/etc/rabbitmq/rabbitmq.conf"
      description: "The config of rabbitmq.conf"
      required: true
      type: "text"
      value: |-
        loopback_users.guest = false
        listeners.tcp.default = 5672
        hipe_compile = false
        management.listener.port = 15672
        management.listener.ssl = false
