isNewTemplate: true

image:
   name: "image"
   description: "Image Info"
   type: "string"
   required: true
   variables:
     image:
       name: "image"
       label: "image"
       description: "The image of app"
       required: true
       value: "registry.harbor:5000/sky-firmament/redis:4.0.2"
       type: "string"    
     policyType:
       name: "policyType"
       label: "policy type"
       description: "The type of image pull policy"
       required: true
       value: "Always"
       type: "string"

resources:
   name: "reosurce info"
   description: "Reosurce Info"
   type: "string"
   required: true
   variables:
     cpuRequest:
       name: "cpuRequest"
       label: "cpu(m)"
       description: "CPU, in cores. (500m = 0.5 cores)"
       required: true
       value: 100
       type: "int"
     memoryRequest:
       name: "memoryRequest"
       label: "memory(MB)"
       description: "Memory, in MB. (1GB = 1024 MB)"
       required: true
       value: 256
       type: "int"

persistence:
   name: "storage"
   description: "Persistent Storage"
   type: "checkbox"
   required: true
   enabled: false
   variables:
     mountPath:
       name: "mountPath"
       label: "Mount Path"
       description: "The path within the container at which the volume should be mounted"
       required: true
       value: "/data"
       type: "string"
     size:
       name: "sizeRequest"
       label: "storage(GB)"
       description: "Storage, in GB. (1GB = 1024 MB)"
       required: true
       value: 1
       type: "int"
     storagePool:
       name: "storagePool"
       label: "storagePool"
       description: "storage pool for volume, use default pool if value is null"
       required: false
       value: ""
       type: "string"

service:
   name: "service"
   description: "Service Info"
   type: "string"
   required: true
   variables:
     type:
       name: "serviceType"
       label: "service type"
       description: "The type of service"
       required: true
       value: "NodePort"
       type: "string"
     port:
       name: "port"
       label: "port"
       description: "The port of service"
       required: true
       value: "6379"
       type: "string"
     nodePort:
       name: "nodePort"
       label: "nodePort"
       description: "The nodePort of service,range 30000-32767"
       required: true
       value: "30379"
       type: "string"
config:
  name: "config"
  description: "custom config"
  type: "text"
  required: true
  variables:
    config: 
      name: "config"
      label: "redis.conf"
      path: "/etc/redis/redis.conf"
      description: "The config of redis.conf"
      required: true
      type: "text"
      value: |-
        appendonly  yes
        protected-mode no
        requirepass password

