kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2alpha1
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "fullname" . }}
  minReplicas: {{ .Values.HPA.variables.minReplicaCount.value }}
  maxReplicas: {{ .Values.HPA.variables.maxReplicaCount.value }}
  metrics:
{{ toYaml .Values.HPA.variables.metrics.value | indent 2 }}
