apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq-ha.fullname" . }}
  labels:
    app: {{ template "rabbitmq-ha.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.variables.httpPort.value }}
      targetPort: http
      {{- if ( and (eq .Values.service.variables.type.value "NodePort") (.Values.service.variables.httpNodePort.value) ) }}
      nodePort: {{ .Values.service.variables.httpNodePort.value }}
      {{- end }}
    - name: amqp
      protocol: TCP
      port: {{ .Values.service.variables.amqpPort.value }}
      targetPort: amqp
      {{- if ( and (eq .Values.service.variables.type.value "NodePort") (.Values.service.variables.amqpNodePort.value) ) }}
      nodePort: {{ .Values.service.variables.amqpNodePort.value }}
      {{- end }}
    - name: epmd
      protocol: TCP
      port: {{ .Values.service.variables.epmdPort.value }}
      targetPort: epmd
      {{- if ( and (eq .Values.service.variables.type.value "NodePort") (.Values.service.variables.epmdNodePort.value) ) }}
      nodePort: {{ .Values.service.variables.epmdNodePort.value }}
      {{- end }}
  selector:
    app: {{ template "rabbitmq-ha.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.variables.type.value }}
