apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq-ha.fullname" . }}-discovery
  labels:
    app: {{ template "rabbitmq-ha.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.variables.httpPort.value }}
      targetPort: http
    - name: amqp
      protocol: TCP
      port: {{ .Values.service.variables.amqpPort.value }}
      targetPort: amqp
    - name: epmd
      protocol: TCP
      port: {{ .Values.service.variables.epmdPort.value }}
      targetPort: epmd
  selector:
    app: {{ template "rabbitmq-ha.name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
