apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  annotations:
     link: >
      [
        {
          "namespace": "default",
          "name": "{{ .Release.Name }}-redis"
        }
      ]
spec:
  replicas: {{ .Values.variables.replicaCount.value }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: REDIS_MASTER_HOST
          value: {{ .Release.Name }}-redis
        - name: REDIS_MASTER_PORT
          value: "6379"
        resources:
{{ toYaml .Values.resources | indent 12 }}
