
isNewTemplate: true

app:
    name: "app"
    description: "app server config"
    type: "string"
    label: "appConfig"
    required: true
    variables:
      replicaCount:
        name: "node number"
        label: "Node number"
        description: "Number of the app"
        required: true
        value: 2
        type: "int"
redis:
    name: "redis"
    description: "redis server config"
    type: "string"
    label: "redisConfig"
    required: true
    variables:
      replicaCount:
        name: "node number"
        label: "Node number"
        description: "Number of the redis"
        required: true
        value: 1
        type: "int"
        
appHpa:
    name: "hpa"
    description: "app autoscaling"
    type: "checkbox"
    required: true
    enabled: false
    variables:
      minReplicas:
        name: "minReplicas"
        label: "minReplicas"
        description: "The minimum replica number of redis"
        required: true
        value: 1
        type: "int"
      maxReplicas:
        name: "maxReplicas"
        label: "maxReplicas"
        description: "The maximum replica number of redis"
        required: true
        value: 3
        type: "int"
      metricName:
        name: "metricName"
        label: "metricName"
        description: "Autoscaling based on custom metrics"
        required: true
        value: "http_requests"
        type: "string"
      targetAverageValue:
        name: "targetAverageValue"
        label: "targetAverageValue"
        description: "Target average value to determine the replica count"
        required: true
        value: "20"
        type: "string"
   
redisHpa:
    name: "hpa"
    description: "redis autoscaling"
    type: "checkbox"
    required: true
    enabled: false
    variables:
      minReplicas:
        name: "minReplicas"
        label: "minReplicas"
        description: "The minimum replica number of redis"
        required: true
        value: 1
        type: "int"
      maxReplicas:
        name: "maxReplicas"
        label: "maxReplicas"
        description: "The maximum replica number of redis"
        required: true
        value: 3
        type: "int"
      metricName:
        name: "metricName"
        label: "metricName"
        description: "Autoscaling based on custom metrics"
        required: true
        value: "redis_memory_used_bytes"
        type: "string"
      targetValue:
        name: "targetValue"
        label: "targetValue"
        description: "Target value to determine the replica count"
        required: true
        value: "512m"
        type: "string"

