{{ if eq .Values.hub.db.type "sqlite-pvc" -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hub-db-dir
  labels:
    app: jupyterhub
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.hub.db.pvc.storageClassName | quote }}
spec:
  {{ if .Values.hub.db.pvc.selector -}}
  selector:
{{ toYaml .Values.hub.db.pvc.selector | indent 4 }}
  {{- end }}
  accessModes:
    {{- range $mode := .Values.hub.db.pvc.accessModes }}
    - {{ $mode }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.hub.db.pvc.storage | quote }}
{{- end }}
