apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  - name: exporter
    port: 9121
    targetPort: exporter
  selector:
    app: {{ template "fullname" . }}
