apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: {{ template "zookeeper.name" . }}
    chart: {{ template "zookeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.variables.type.value }}
  ports:
  - port: {{ .Values.service.variables.externalPort.value }}
    targetPort: client
    protocol: TCP
    name: client
 {{- if ( and (eq .Values.service.variables.type.value "NodePort") (.Values.service.variables.nodePort.value) ) }}
    nodePort: {{ .Values.service.variables.nodePort.value }}
 {{- end }}
  selector:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
