apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: {{ template "zookeeper.name" . }}
    chart: {{ template "zookeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: server
spec:
  serviceName: {{ template "zookeeper.fullname" . }}-headless
  replicas: {{ .Values.replica.variables.count.value }}
  selector:
    matchLabels:
      app: {{ template "zookeeper.name" . }}
      release: {{ .Release.Name }}
      component: server
  template:
    metadata:
      labels:
        app: {{ template "zookeeper.name" . }}
        release: {{ .Release.Name }}
        component: server
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: zookeeper
          image: "{{ .Values.image.variables.image.value }}"
          imagePullPolicy: {{ .Values.image.variables.policyType.value | quote }}
          command:
            - /bin/bash
            - -xec
            - zkGenConfig.sh && exec zkServer.sh start-foreground
          ports:
          - name: client
            containerPort: 2181
            protocol: TCP
          - name: election
            containerPort: 3888
            protocol: TCP
          - name: server
            containerPort: 2888
            protocol: TCP
          livenessProbe:
            exec:
              command:
                - zkOk.sh
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - zkOk.sh
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 6
            successThreshold: 1
          env:
            - name: ZK_REPLICAS
              value: {{ .Values.replica.variables.count.value | quote }}
            - name: JMXAUTH
              value: "false"
            - name: JMXDISABLE
              value: "false"
            - name: JMXPORT
              value: "1099"
            - name: JMXSSL
              value: "false"
            - name: ZK_CLIENT_PORT
              value: "2181"
            - name: ZK_ELECTION_PORT
              value: "3888"
            - name: ZK_HEAP_SIZE
              value: 2G
            - name: ZK_INIT_LIMIT
              value: "5"
            - name: ZK_LOG_LEVEL
              value: INFO
            - name: ZK_MAX_CLIENT_CNXNS
              value: "60"
            - name: ZK_MAX_SESSION_TIMEOUT
              value: "40000"
            - name: ZK_MIN_SESSION_TIMEOUT
              value: "4000"
            - name: ZK_PURGE_INTERVAL
              value: "0"
            - name: ZK_SERVER_PORT
              value: "2888"
            - name: ZK_SNAP_RETAIN_COUNT
              value: "3"
            - name: ZK_SYNC_LIMIT
              value: "10"
            - name: ZK_TICK_TIME
              value: "2000"
          resources:
            requests:
              cpu: {{ .Values.resources.variables.cpuRequest.value }}m
              memory: {{ .Values.resources.variables.memoryRequest.value }}Mi
 {{- if .Values.persistence.enabled -}}
          volumeMounts:
            - name: data
              mountPath: /var/lib/zookeeper
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ .Values.persistence.variables.accessMode.value | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.variables.size.value }}Gi
      {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.variables.storageClass.value) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.variables.storageClass.value }}"
        {{- end }}
      {{- end }}
 {{- end }}
